// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlebldostkltxfrzmtha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZWJsZG9zdGtsdHhmcnptdGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzY0MjEsImV4cCI6MjA2MDIxMjQyMX0.qmWHllep-gZSZ3sdFfVsxGu5uzhkSAPKLv4HsBCNLz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);